#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Run ESLint
npm run lint

# Run Prettier
npm run format

# If everything passes... Now we can commit
echo '✅✅ You win this time... I am committing this now. ✅✅'